### ISSUE TITLE
How did you input the text descriptions into your models?

### ISSUE THREAD

**Issue by ngthanhtin** [Glaciohound/CLORE#2]
Hi @Glaciohound ,

In your reported results with the CUB dataset here:
![Screenshot 2023-07-17 at 11 05 22 AM](https://github.com/Glaciohound/CLORE/assets/17596799/ca100802-748d-4a5f-bbb2-e4b4ba275d1a)

For CLIP_finetune, CLIP_linear, and CLORE_CLIP, did you input the text descriptions into your model as provided [here](https://github.com/Glaciohound/CLORE/blob/main/guidelines/CUB/definitions.txt) OR you included the class_name into all your descriptions?

I ask this because class names are very important for CLIP to classify images.

Thank you for your paper.

Best,
Tin

**Comment by Glaciohound** [comment]
Hello Tin. Nice to hear from you! Thanks for your interests in our work. For this baseline, we indeed used the descriptions in the `guidelines/CUB/definitions.txt` file, which already includes class names in many (not all) descriptions. So CLIP can access the class name information from inputs even without further emphasizing. Let us know if you have other questions.

Chi

**Comment by ngthanhtin** [comment]
Thank for you clarification.
