### ISSUE TITLE
Pretrained Model?

### ISSUE THREAD

**Issue by ngthanhtin** [Glaciohound/CLORE#3]
Hi @Glaciohound ,

Thank you for providing more guidance on how to use your code last time.

For now, I want to reproduce your results and apply my descriptions to your model to test the performance of our descriptions. So could you please share your pre-trained model on CUB? 
It would be really help for my research.

Thank you,
 Best,
Tin

**Comment by Glaciohound** [comment]
Hi Tin,

Sure, the a Google Drive link to our checkpoint is here: https://drive.google.com/file/d/1sr74BYFyoqoDk0vJ5UYGYVUcZyAzr7Z7/view?usp=share_link.

It was trained using the CLORE command in our `README.md`. I copy it here:

```
CUB_DATA=./cub_data/
LOG_DIR=./logs/
TRIAL_ID=clore_cub
SPLIT_FILE=guidelines/CUB/att_splits.mat
PYTHONPATH=. CUDA_VISIBLE_DEVICES=0 python experiments/cub_definitions.py \
    --output_dir $LOG_DIR/${TRIAL_ID} --data_dir $CUB_DATA/images \
    --split_file $SPLIT_FILE \
    --definition_file guidelines/CUB/definitions.txt \
    --class_names_file guidelines/CUB/CUB_classes.txt \
    --model_name_or_path bert-base-uncased --vision_model IMAGENET1K_V2 --num_train_epochs 10 --learning_rate 1e-4 --seed 1 \
    --per_device_train_batch_size 32 --per_device_eval_batch_size 64 \
    --phase fix_bert --do_eval --do_test \
    --guideline_feature_layer_num_head 4 --encoder_feature_layer_num_head 4
```


Best,

Chi

**Comment by ngthanhtin** [comment]
Thank you so much!

Best,
Tin

**Comment by Glaciohound** [comment]
Please also refer to updated response above, and pull the newest version of the repo for the codes to be compatible with the checkpoint.

**Comment by ngthanhtin** [comment]
Hi @Glaciohound ,
I pulled the latest code from your repo, and download the weights you provided and put it in `logs/clore_cub/`, and run the above provided code, but I got the error like this, could you check your provided weight, thank you so much!
<img width="723" alt="Screenshot 2023-08-15 at 4 47 26 PM" src="https://github.com/Glaciohound/CLORE/assets/17596799/6bbf44d9-f9ec-4b73-9e10-703178cea67f">

**Comment by Glaciohound** [comment]
This is weird.

From my side the code is running properly.

From the code it seems that `guideline_encoder.embeddings.position_ids` is missing in the model architecture (which is wrong), but is provided in the checkpoint (which is correct).

Can you check two things:
1. Can you confirm you did not run the clip-related commands (i.e., `--vision_model` is not `clip`, and you did not specify `--clip` argument)
2. Can you add a line `print(model)` before checkpoint loading to see what is the exact architecture of the model, so we can see which part is missing in the model construction?

**Comment by ngthanhtin** [comment]
Hi @Glaciohound , I cloned the repo again and I can run the code now. Thank you so much!
